# Generated by Django 3.0.6 on 2021-01-06 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('pronunciation', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('V', 'Verb'), ('N', 'Noun'), ('ADV', 'Adverb'), ('ADJ', 'Adjective'), ('PHV', 'Phrasal verb'), ('OTH', 'Other')], default='N', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning_text', models.CharField(max_length=200)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Token')),
            ],
        ),
    ]
