# Generated by Django 3.0.6 on 2021-01-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meaning',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
