# Generated by Django 3.0.6 on 2021-01-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_meaning_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meaning',
            name='order',
            field=models.IntegerField(unique=True),
        ),
    ]
